image: node:latest

cache:
  paths:
    - node_modules
  key:
    files:
      - yarn.lock

pages:
  stage: deploy
  script:
    - yarn install --frozen-lockfile
    - yarn add --dev @expo/webpack-config
    - npx expo export:web && mv web-build public
  artifacts:
    paths:
      - public/
    expire_in: '1 second'
  only:
    - main